
name: auditflow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - plotly
  - fpdf
  - pytesseract
  - pillow
  - pymupdf
  - scikit-learn
  - openpyxl
  - pip
  - pip:
      - openai
