name: auditflow_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - pandas
      - plotly
      - PyMuPDF
      - openai
      - langdetect
      - fpdf
      - reportlab
      - matplotlib
      - scikit-learn
      - openpyxl
